#!/usr/bin/env python3

import sys

if sys.version_info.major < 3 or (
    sys.version_info.major == 3 and sys.version_info.minor < 5
):
    sys.stderr.write("ERROR: frcutils requires Python 3.5+\n")
    exit(1)

import os
from os.path import dirname, exists, join
import subprocess
from setuptools import find_packages, setup

setup_dir = dirname(__file__)
git_dir = join(setup_dir, ".git")
base_package = "frcutils"
version_file = join(setup_dir, "lib", base_package, "version.py")

# Automatically generate a version.py based on the git version
if exists(git_dir):
    p = subprocess.Popen(
        ["git", "describe", "--tags", "--long", "--dirty=-dirty"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    out, err = p.communicate()
    # Make sure the git version has at least one tag
    if err:
        print("Error: You need to create a tag for this repo to use the builder")
        sys.exit(1)

    # Convert git version to PEP440 compliant version
    # - Older versions of pip choke on local identifiers, so we can't include the git commit
    v, commits, local = out.decode("utf-8").rstrip().split("-", 2)
    if commits != "0" or "-dirty" in local:
        v = "%s.post0.dev%s" % (v, commits)

    # Create the version.py file
    with open(version_file, "w") as fp:
        fp.write("# Autogenerated by setup.py\n__version__ = '{0}'".format(v))

if exists(version_file):
    with open(version_file, "r") as fp:
        exec(fp.read(), globals())
else:
    __version__ = "master"

with open(join(setup_dir, "requirements.txt")) as requirements_file:
    install_requires = requirements_file.readlines()

with open(join(dirname(__file__), "README.md"), "r") as readme_file:
    long_description = readme_file.read()

setup(
    name="frcutils",
    version=__version__,
    description="Utility library for FRC",
    long_description=long_description,
    author="FRC 1418",
    author_email="robotics1418@gmail.com",
    url="https://github.com/frc1418/frcutils",
    license="MIT",
    packages=find_packages(where="lib"),
    package_dir={"": "lib"},
    include_package_data=True,
    install_requires=install_requires,
    classifiers=[
        "Development Status :: 1 - Planning",
        "Framework :: Robot Framework :: Library",
        "Framework :: Robot Framework :: Tool",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    entry_points={
        "console_scripts": [
            "generate-robot = generation.robotproject:generate",
        ],
        "robotpy": [
            "dep = deployment.deploy:FRCUtilDeploy"
        ]
    },
)
